export const GET_ERRORS = "GET_ERRORS";
export const FETCH_COURSE = "FETCH_COURSE";
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSE_SELECT = "FETCH_COURSE_SELECT"
export const FETCH_COURSE_MOST_VIEWED = "FETCH_COURSE_MOST_VIEWED";
export const SET_COURSE_LOADING = "SET_COURSE_LOADING"
export const SET_LOADING = "SET_LOADING"

export const FETCH_CATEGORY = "FETCH_CATEGORY"

export const FETCH_USERS = "FETCH_USERS"