export const GET_ERRORS = "GET_ERRORS";
export const FETCH_COURSE = "FETCH_COURSE";
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSE_SELECT = "FETCH_COURSE_SELECT"
export const FETCH_COURSE_MOST_VIEWED = "FETCH_COURSE_MOST_VIEWED";
export const SET_COURSE_LOADING = "SET_COURSE_LOADING";
export const SET_LOADING = "SET_LOADING";
export const SET_COURSE_SUBBED = "SET_COURSE_SUBBED"
export const SET_COURSE_WATCHED ="SET_COURSE_WATCHED"
export const SET_COURSE_OWNED = "SET_COURSE_OWNED"

export const FETCH_COURSE_LATEST = "FETCH_COURSE_LATEST";
export const FETCH_COURSE_WEEK_HIGHLIGHT = "FETCH_COURSE_WEEK_HIGHLIGHT";
export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS"

export const FETCH_CATEGORY = "FETCH_CATEGORY";


export const FETCH_USERS = "FETCH_USERS"
export const FETCH_WATCHLIST = "FETCH_WATCHLIST"
export const FETCH_SUBSCRIPTION = "FETCH_SUBSCRIPTION"
export const FETCH_LECTURER_COURSES = "FETCH_LECTURER_COURSES"